import type { FontCategory, FontFamilyOption } from "./state-types"

const SANS_FONT_LABELS = [
  "Inter",
  "Roboto",
  "Poppins",
  "Geist",
  "Outfit",
  "Space Grotesk",
  "Nunito",
  "Raleway",
  "Oswald",
  "Doto",
  "ABeeZee",
  "Abel",
  "Aclonica",
  "Acme",
  "Actor",
  "Advent Pro",
  "Afacad",
  "Afacad Flux",
  "Agdasima",
  "Akatab",
  "Akshar",
  "Alan Sans",
  "Alata",
  "Alatsi",
  "Albert Sans",
  "Aldrich",
  "Alef",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Alexandria",
  "Allerta",
  "Allerta Stencil",
  "Almarai",
  "Alumni Sans",
  "Alumni Sans Collegiate One",
  "Alumni Sans Pinstripe",
  "Alumni Sans SC",
  "Amaranth",
  "Amarna",
  "Amiko",
  "Anaheim",
  "Ancizar Sans",
  "Andika",
  "Anek Bangla",
  "Anek Devanagari",
  "Anek Gujarati",
  "Anek Gurmukhi",
  "Anek Kannada",
  "Anek Latin",
  "Anek Malayalam",
  "Anek Odia",
  "Anek Tamil",
  "Anek Telugu",
  "Anta",
  "Antic",
  "Anton",
  "Anton SC",
  "Antonio",
  "Anuphan",
  "AR One Sans",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Arimo",
  "Armata",
  "Arsenal",
  "Arsenal SC",
  "Arya",
  "Asap",
  "Asap Condensed",
  "Asimovian",
  "Assistant",
  "Asta Sans",
  "Athiti",
  "Atkinson Hyperlegible",
  "Atkinson Hyperlegible Mono",
  "Atkinson Hyperlegible Next",
  "Average Sans",
  "B612",
  "Bai Jamjuree",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Basic",
  "Bayon",
  "BBH Bartle",
  "BBH Bogle",
  "BBH Hegarty",
  "Be Vietnam Pro",
  "Bebas Neue",
  "Beiruti",
  "Belanosima",
  "Belleza",
  "BenchNine",
  "Biryani",
  "BIZ UDGothic",
  "BIZ UDPGothic",
  "Black Han Sans",
  "Blinker",
  "Cabin",
] as const

const SERIF_FONT_LABELS = [
  "Playfair Display",
  "Lora",
  "Abhaya Libre",
  "Abyssinica SIL",
  "Adamina",
  "Alegreya",
  "Alegreya SC",
  "Aleo",
  "Alice",
  "Alike",
  "Alike Angular",
  "Alkalami",
  "Almendra",
  "Almendra SC",
  "Alyamama",
  "Amethysta",
  "Amiri",
  "Amiri Quran",
  "Ancizar Serif",
  "Andada Pro",
  "Annapurna SIL",
  "Antic Didone",
  "Antic Slab",
  "Aoboshi One",
  "Arapey",
  "Arbutus",
  "Arbutus Slab",
  "Aref Ruqaa",
  "Aref Ruqaa Ink",
  "Artifika",
  "Arvo",
  "Asar",
  "Asul",
  "Average",
  "Bacasime Antique",
  "Balthazar",
  "Baskervville",
  "Baskervville SC",
  "Belgrano",
  "Bellefair",
  "Benne",
  "Bentham",
  "Besley",
  "Bevan",
  "BhuTuka Expanded One",
  "BioRhyme",
  "BioRhyme Expanded",
  "Bitter",
  "BIZ UDMincho",
  "BIZ UDPMincho",
  "BJCree",
  "Bodoni Moda",
  "Bodoni Moda SC",
  "Bona Nova",
  "Bona Nova SC",
  "Brawler",
  "Bree Serif",
  "Brygada 1918",
  "Buenard",
  "Cactus Classical Serif",
  "Caladea",
  "Cambo",
  "Cantata One",
  "Cardo",
  "Castoro",
  "Caudex",
  "Charis SIL",
  "Chiron Sung HK",
  "Cinzel",
  "Copse",
  "Cormorant",
  "Cormorant Garamond",
  "Cormorant Infant",
  "Cormorant SC",
  "Cormorant Unicase",
  "Cormorant Upright",
  "Coustard",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "Cutive",
  "Dai Banna SIL",
  "Danfo",
  "David Libre",
  "Della Respira",
  "Diphylleia",
  "DM Serif Display",
  "DM Serif Text",
  "Domine",
  "Donegal One",
  "EB Garamond",
  "Eczar",
  "Enriqueta",
  "Epunda Slab",
  "Esteban",
  "Fanwood Text",
  "Fauna One",
  "Faustina",
  "Fraunces",
  "Gelasio",
] as const

const GOOGLE_MONO_LABELS = [
  "Fira Code",
  "Anonymous Pro",
  "Azeret Mono",
  "B612 Mono",
  "Chivo Mono",
  "Courier Prime",
  "Cousine",
  "Cutive Mono",
  "Datatype",
  "DM Mono",
  "Fira Mono",
  "Fragment Mono",
  "Geist Mono",
  "Google Sans Code",
  "IBM Plex Mono",
  "Inconsolata",
  "Intel One Mono",
  "Iosevka Charon",
  "Iosevka Charon Mono",
  "JetBrains Mono",
  "Kode Mono",
  "Lekton",
  "Libertinus Mono",
  "Lilex",
  "LXGW WenKai Mono TC",
  "M PLUS 1 Code",
  "Major Mono Display",
  "Martian Mono",
  "Monofett",
  "Nova Mono",
  "Overpass Mono",
  "Oxygen Mono",
  "PT Mono",
  "Red Hat Mono",
  "Reddit Mono",
  "Roboto Mono",
  "Share Tech Mono",
  "Sixtyfour",
  "Sixtyfour Convergence",
  "Sometype Mono",
  "Source Code Pro",
  "Space Mono",
  "Spline Sans Mono",
  "Syne Mono",
  "Ubuntu Mono",
  "Ubuntu Sans Mono",
  "Victor Mono",
  "VT323",
  "Workbench",
  "Xanh Mono",
] as const

const EXTRA_MONO_LABELS = [
  "SF Mono",
  "Menlo",
  "Monaco",
  "Consolas",
  "Cascadia Code",
  "Cascadia Mono",
  "Hack",
  "Hasklig",
  "Input Mono",
  "PragmataPro",
  "Dank Mono",
  "Operator Mono",
  "Berkeley Mono",
  "Commit Mono",
  "Cartograph CF",
  "Monaspace Argon",
  "Monaspace Neon",
  "Monaspace Xenon",
  "Monaspace Radon",
  "Monaspace Krypton",
  "Iosevka",
  "Recursive Mono",
  "DejaVu Sans Mono",
  "Liberation Mono",
  "Noto Sans Mono",
  "Andale Mono",
  "Droid Sans Mono",
  "Meslo LG",
  "Proggy Clean",
  "Terminus",
  "Anonymous",
  "Code New Roman",
  "Cascadia Code PL",
  "Cascadia Mono PL",
  "IBM 3270",
  "Monoid",
  "Agave",
  "Envy Code R",
  "Sudo",
  "Fixedsys Excelsior",
  "Inziu Iosevka",
  "Ubuntu Mono Nerd Font",
  "JetBrains Mono NL",
  "Victor Mono Nerd Font",
  "Sarasa Mono",
  "Tamsyn",
  "Go Mono",
  "PT Root UI Mono",
  "Maple Mono",
  "Recursive",
] as const

const SCRIPT_FONT_LABELS = [
  "Dancing Script",
  "Caveat",
  "Aguafina Script",
  "Alex Brush",
  "Allison",
  "Allura",
  "Amatic SC",
  "Amita",
  "Annie Use Your Telescope",
  "Architects Daughter",
  "Are You Serious",
  "Arizonia",
  "Babylonica",
  "Bad Script",
  "Ballet",
  "Beau Rivage",
  "Berkshire Swash",
  "Betania Patmos",
  "Betania Patmos GDL",
  "Betania Patmos In",
  "Betania Patmos In GDL",
  "Beth Ellen",
  "Bilbo",
  "Bilbo Swash Caps",
  "Birthstone",
  "Birthstone Bounce",
  "Bonbon",
  "Bonheur Royale",
  "Borel",
  "Bpmf Iansui",
  "Butterfly Kids",
  "Calligraffitti",
  "Caramel",
  "Carattere",
  "Cause",
  "Caveat Brush",
  "Cedarville Cursive",
  "Charm",
  "Charmonman",
  "Cherish",
  "Chilanka",
  "Clicker Script",
  "Comforter",
  "Comforter Brush",
  "Comic Neue",
  "Coming Soon",
  "Condiment",
  "Cookie",
  "Corinthia",
  "Courgette",
  "Covered By Your Grace",
  "Crafty Girls",
  "Damion",
  "Dawning of a New Day",
  "Dekko",
  "Delicious Handrawn",
  "Delius",
  "Delius Swash Caps",
  "Delius Unicase",
  "Devonshire",
  "Dr Sugiyama",
  "Eagle Lake",
  "East Sea Dokdo",
  "Edu AU VIC WA NT Arrows",
  "Edu AU VIC WA NT Dots",
  "Edu AU VIC WA NT Guides",
  "Edu AU VIC WA NT Hand",
  "Edu AU VIC WA NT Pre",
  "Edu NSW ACT Cursive",
  "Edu NSW ACT Foundation",
  "Edu NSW ACT Hand Pre",
  "Edu QLD Beginner",
  "Edu QLD Hand",
  "Edu SA Beginner",
  "Edu SA Hand",
  "Edu TAS Beginner",
  "Edu VIC WA NT Beginner",
  "Edu VIC WA NT Hand",
  "Edu VIC WA NT Hand Pre",
  "Engagement",
  "Ephesis",
  "Estonia",
  "Euphoria Script",
  "Explora",
  "Felipa",
  "Festive",
  "Fleur De Leah",
  "Fondamento",
  "Fuggles",
  "Fuzzy Bubbles",
  "Gaegu",
  "Gamja Flower",
  "Give You Glory",
  "Gloria Hallelujah",
  "Gochi Hand",
  "Grand Hotel",
  "Grape Nuts",
  "Great Vibes",
  "Grechen Fuemen",
  "Grey Qo",
] as const

function toFontId(label: string, category: FontCategory) {
  const slug = label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
  return `${category}-${slug || "font"}`
}

function makeCss(label: string, category: FontCategory) {
  if (label === "Doto") return "var(--font-doto), 'Doto', sans-serif"
  const quoted = `'${label.replace(/'/g, "\\'")}'`
  if (category === "serif") return `${quoted}, serif`
  if (category === "mono") return `${quoted}, ui-monospace, monospace`
  if (category === "script") return `${quoted}, cursive`
  return `${quoted}, sans-serif`
}

function buildFontOptions(
  labels: readonly string[],
  category: FontCategory
): FontFamilyOption[] {
  return labels.slice(0, 100).map((label) => ({
    id: toFontId(label, category),
    label,
    css: makeCss(label, category),
    category,
  }))
}

export const FONT_FAMILIES: FontFamilyOption[] = [
  ...buildFontOptions(SANS_FONT_LABELS, "sans"),
  ...buildFontOptions(SERIF_FONT_LABELS, "serif"),
  ...buildFontOptions([...GOOGLE_MONO_LABELS, ...EXTRA_MONO_LABELS], "mono"),
  ...buildFontOptions(SCRIPT_FONT_LABELS, "script"),
  {
    id: "system-serif",
    label: "System Serif",
    css: "Georgia, 'Times New Roman', serif",
    category: "system",
  },
  {
    id: "system-ui",
    label: "System UI",
    css: "system-ui, sans-serif",
    category: "system",
  },
]
